[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "notebooks"
version = "0.1.0"
dependencies = [
    "pyspark",
    "pandas"

]

[tool.setuptools.packages.find]
where = ["src"]

